### ISSUE TITLE
Questions/Comments about tests/core/unittests/experiment.yaml

### ISSUE THREAD

**Issue by bouthilx** [mila-udem/metaopt#20]
It's not clear to me how the experiment documents are structure based on the yaml file. What is references precisely?

I would not add this in the DB. It can be computed on the fly.
+  stats:
+    trials_completed: 0
+    best_trial_id: ~
+    start_time: 123
+    end_time: ~
+    duration: ~

For workers and especially for ressources I cannot say. This part of the project is not clear enough for me now to think about the DB structure for them.

**Comment by tsirif** [comment]
Summarizing discussion on slack 2017/12/1:

- [ ] **Key `refers`** is to be used in referencing other source of relevant trials' history. User ought to complete the hyperparameters missing with a constant number/enum, if the referent experiment's hyperparameter space is a projection of the referrer's one. Argue the difficulty of parsing a directed graph structure like this, perhaps restricting to a tree (one exp can have only on referent) could help. Currently, leave it unimplemented - to be discussed.
- [ ] **Stats** can be a property (not implemented for now) that computes on the fly its attributes from Trial history in database. It doesn't need to be saved in database.
- [ ] Discuss about logging **resources**(schedulers) and **workers**.

**Comment by bouthilx** [comment]
Thanks a lot for the summary!
