### ISSUE TITLE
Implement database feature: Should have a `count` method 

### ISSUE THREAD

**Issue by tsirif** [mila-udem/metaopt#25]
I found a need to use an immediate `count` method for a specific collection in a database, in order to expose an API from `Experiment` that checks whether an experiment has reached terminating condition implied by attribute `max_trials`. I foresee that it will be useful in `Worker`'s implementation. See tsirif@685ee9ac and [line 123](https://github.com/mila-udem/metaopt/pull/21/commits/685ee9ac31961d003233a8a854f5dc307d1cf12f#diff-a2a3290c5b4afca6e22d8bff4b3d5f5eR123).

Relevant issues: #21

**Comment by bouthilx** [comment]
Agreed. We could use ```len(read(query))``` for now however. It's less efficient but no additional unit-test and maintenance are required. :wink:

**Comment by tsirif** [comment]
Come ooooon
