### ISSUE TITLE
Make trial selections atomic

### ISSUE THREAD

**Issue by bouthilx** [mila-udem/metaopt#42]
When a trial is selected, it will completely overwrite the database row when setting status to reserved. However, there could be a race condition meanwhile and another process could have written the row already. To avoid this, the query in write() should ensure that the status is the one we get from the first read(). If the query fails, the method needs to retry another reservation. We can assume that trials' db row cannot change if status is not 'reserved', so such a query would be sufficient to ensure atomicity (if underlying's database code is something like find_and_update).

```python
aknowledged = self._db.write('trials', selected_trial.to_dict(),
                             query={'_id': selected_trial.id,
                                    'status': selected_trial.status})
if not aknowledged:
    return self.reserve_trial(score_handle)

return selected_trial
```

**Comment by nouiz** [comment]
This is an important problem. Hopefully it can be fixed soon.
