### ISSUE TITLE
What should `random` keyword in hyperparameter domain declaration mean?

### ISSUE THREAD

**Issue by tsirif** [mila-udem/metaopt#48]
X:
> The support for Real, Integer and Categorical by random() is very confusing. If no features are added for Real and Integer by random(), I would support only Categorical. Also, if enum and random support identical features for Categorical, we should drop one or the other. I think random() is a better fit because of the probabilities argument.

C:
> I have no argument against this. Also, I agree that random should preferably mean one thing... Constraints on polymorphism.

**Comment by bouthilx** [comment]
For reference, we agreed on todays meeting that we will keep `choices()` only to define distributions of Categories. `choices()` will also support probability distributions.

**Comment by tsirif** [comment]
@bouthilx So just to be sure:
1. Delete [`random`](https://github.com/tsirif/metaopt/blob/feature/algorithm/src/metaopt/core/io/space_builder.py#L125).
2. Rename [`enum`](https://github.com/tsirif/metaopt/blob/feature/algorithm/src/metaopt/core/io/space_builder.py#L113) to `choices`?
